'use client';
import * as React from 'react';
import { DataGrid } from 'twine-ui';

const columns = [
  { field: 'city', headerName: 'City', width: 180 },
  { field: 'state', headerName: 'State', width: 100 },
  { field: 'zip', headerName: 'ZIP', width: 120 },
  { field: 'county', headerName: 'County', width: 180 },
  { field: 'timezone', headerName: 'Timezone', width: 140 },
  { field: 'lat', headerName: 'Lat', width: 120, align: 'right' as const },
  { field: 'lng', headerName: 'Lng', width: 120, align: 'right' as const },
  {
    field: 'population',
    headerName: 'Population',
    width: 140,
    align: 'right' as const,
  },
  { field: 'areaCode', headerName: 'Area Code', width: 120 },
  { field: 'metro', headerName: 'Metro', width: 200 },
];

const rows = [
  {
    id: 1,
    city: 'Austin',
    state: 'TX',
    zip: '73301',
    county: 'Travis',
    timezone: 'CST',
    lat: 30.27,
    lng: -97.74,
    population: 964177,
    areaCode: '512',
    metro: 'Austin–Round Rock',
  },
  {
    id: 2,
    city: 'Denver',
    state: 'CO',
    zip: '80014',
    county: 'Denver',
    timezone: 'MST',
    lat: 39.74,
    lng: -104.99,
    population: 711463,
    areaCode: '303',
    metro: 'Denver–Aurora',
  },
  {
    id: 3,
    city: 'Raleigh',
    state: 'NC',
    zip: '27601',
    county: 'Wake',
    timezone: 'EST',
    lat: 35.78,
    lng: -78.64,
    population: 474414,
    areaCode: '919',
    metro: 'Raleigh–Cary',
  },
  {
    id: 4,
    city: 'Portland',
    state: 'OR',
    zip: '97201',
    county: 'Multnomah',
    timezone: 'PST',
    lat: 45.52,
    lng: -122.68,
    population: 635067,
    areaCode: '503',
    metro: 'Portland–Vancouver',
  },
  {
    id: 5,
    city: 'Seattle',
    state: 'WA',
    zip: '98101',
    county: 'King',
    timezone: 'PST',
    lat: 47.61,
    lng: -122.33,
    population: 749256,
    areaCode: '206',
    metro: 'Seattle–Tacoma',
  },
  {
    id: 6,
    city: 'Chicago',
    state: 'IL',
    zip: '60601',
    county: 'Cook',
    timezone: 'CST',
    lat: 41.88,
    lng: -87.63,
    population: 2696555,
    areaCode: '312',
    metro: 'Chicago–Naperville',
  },
  {
    id: 7,
    city: 'Phoenix',
    state: 'AZ',
    zip: '85001',
    county: 'Maricopa',
    timezone: 'MST',
    lat: 33.45,
    lng: -112.07,
    population: 1624566,
    areaCode: '602',
    metro: 'Phoenix–Mesa',
  },
  {
    id: 8,
    city: 'Miami',
    state: 'FL',
    zip: '33101',
    county: 'Miami-Dade',
    timezone: 'EST',
    lat: 25.76,
    lng: -80.19,
    population: 449514,
    areaCode: '305',
    metro: 'Miami–Fort Lauderdale',
  },
  {
    id: 9,
    city: 'Boston',
    state: 'MA',
    zip: '02108',
    county: 'Suffolk',
    timezone: 'EST',
    lat: 42.36,
    lng: -71.06,
    population: 654776,
    areaCode: '617',
    metro: 'Boston–Cambridge',
  },
  {
    id: 10,
    city: 'Nashville',
    state: 'TN',
    zip: '37201',
    county: 'Davidson',
    timezone: 'CST',
    lat: 36.16,
    lng: -86.78,
    population: 715884,
    areaCode: '615',
    metro: 'Nashville–Davidson',
  },
  {
    id: 11,
    city: 'Dallas',
    state: 'TX',
    zip: '75201',
    county: 'Dallas',
    timezone: 'CST',
    lat: 32.78,
    lng: -96.8,
    population: 1304379,
    areaCode: '214',
    metro: 'Dallas–Fort Worth',
  },
  {
    id: 12,
    city: 'San Jose',
    state: 'CA',
    zip: '95113',
    county: 'Santa Clara',
    timezone: 'PST',
    lat: 37.34,
    lng: -121.89,
    population: 971233,
    areaCode: '408',
    metro: 'San Jose–Sunnyvale',
  },
  {
    id: 13,
    city: 'Atlanta',
    state: 'GA',
    zip: '30303',
    county: 'Fulton',
    timezone: 'EST',
    lat: 33.75,
    lng: -84.39,
    population: 507627,
    areaCode: '404',
    metro: 'Atlanta–Sandy Springs',
  },
  {
    id: 14,
    city: 'Minneapolis',
    state: 'MN',
    zip: '55401',
    county: 'Hennepin',
    timezone: 'CST',
    lat: 44.98,
    lng: -93.27,
    population: 425336,
    areaCode: '612',
    metro: 'Minneapolis–St. Paul',
  },
  {
    id: 15,
    city: 'Houston',
    state: 'TX',
    zip: '77002',
    county: 'Harris',
    timezone: 'CST',
    lat: 29.76,
    lng: -95.37,
    population: 2302878,
    areaCode: '713',
    metro: 'Houston–The Woodlands',
  },
  {
    id: 16,
    city: 'San Diego',
    state: 'CA',
    zip: '92101',
    county: 'San Diego',
    timezone: 'PST',
    lat: 32.72,
    lng: -117.16,
    population: 1386932,
    areaCode: '619',
    metro: 'San Diego–Carlsbad',
  },
  {
    id: 17,
    city: 'Charlotte',
    state: 'NC',
    zip: '28202',
    county: 'Mecklenburg',
    timezone: 'EST',
    lat: 35.23,
    lng: -80.84,
    population: 897720,
    areaCode: '704',
    metro: 'Charlotte–Concord',
  },
  {
    id: 18,
    city: 'Cleveland',
    state: 'OH',
    zip: '44114',
    county: 'Cuyahoga',
    timezone: 'EST',
    lat: 41.5,
    lng: -81.69,
    population: 361607,
    areaCode: '216',
    metro: 'Cleveland–Elyria',
  },
  {
    id: 19,
    city: 'Salt Lake City',
    state: 'UT',
    zip: '84101',
    county: 'Salt Lake',
    timezone: 'MST',
    lat: 40.76,
    lng: -111.89,
    population: 205833,
    areaCode: '801',
    metro: 'Salt Lake City',
  },
  {
    id: 20,
    city: 'Philadelphia',
    state: 'PA',
    zip: '19103',
    county: 'Philadelphia',
    timezone: 'EST',
    lat: 39.95,
    lng: -75.16,
    population: 1567442,
    areaCode: '215',
    metro: 'Philadelphia–Camden',
  },
];

export const DataGridColumnDragResizeDemo: React.FC = () => {
  return (
    <div className="w-full">
      <DataGrid
        rows={rows}
        columns={columns}
        pageSize={10}
        enableColumnReorder
        enableColumnResize
        showFooter
      />
    </div>
  );
};
