export const demoData = [
  {
    id: 1,
    name: 'John Doe',
    email: 'john@example.com',
    username: 'johnd',
    role: 'Admin',
    status: 'Active',
    lastLogin: '2025-08-10',
  },
  {
    id: 2,
    name: 'Jane Smith',
    email: 'jane@example.com',
    username: 'janes',
    role: 'User',
    status: 'Active',
    lastLogin: '2025-08-11',
  },
  {
    id: 3,
    name: 'Bob Johnson',
    email: 'bob@example.com',
    username: 'bobj',
    role: 'Editor',
    status: 'Suspended',
    lastLogin: '2025-07-30',
  },
  {
    id: 4,
    name: 'Alice Brown',
    email: 'alice@example.com',
    username: 'aliceb',
    role: 'User',
    status: 'Active',
    lastLogin: '2025-08-12',
  },
  {
    id: 5,
    name: 'Charlie Green',
    email: 'charlie@example.com',
    username: 'charlieg',
    role: 'Admin',
    status: 'Inactive',
    lastLogin: '2025-06-25',
  },
  {
    id: 6,
    name: 'Diana White',
    email: 'diana@example.com',
    username: 'dianaw',
    role: 'Editor',
    status: 'Active',
    lastLogin: '2025-08-05',
  },
  {
    id: 7,
    name: 'Ethan Black',
    email: 'ethan@example.com',
    username: 'ethanb',
    role: 'User',
    status: 'Active',
    lastLogin: '2025-08-09',
  },
  {
    id: 8,
    name: 'Fiona Gray',
    email: 'fiona@example.com',
    username: 'fionag',
    role: 'Editor',
    status: 'Suspended',
    lastLogin: '2025-07-15',
  },
  {
    id: 9,
    name: 'George King',
    email: 'george@example.com',
    username: 'georgek',
    role: 'User',
    status: 'Active',
    lastLogin: '2025-08-01',
  },
  {
    id: 10,
    name: 'Hannah Lee',
    email: 'hannah@example.com',
    username: 'hannahl',
    role: 'Admin',
    status: 'Active',
    lastLogin: '2025-08-13',
  },
];
